
server:
  shutdown: graceful

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3308/adgile_user?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: root
    password: 1234
    schemas: adgile_user
    url: jdbc:mysql://localhost:3308/adgile_user?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

#logging:
#  config: classpath:logback-local.xml